create database heritage;
use heritage;

-- 공지사항
DROP TABLE IF EXISTS notice;
CREATE TABLE notice (
	pk INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    writer VARCHAR(100) NOT NULL,
    content VARCHAR(10000) DEFAULT NULL,
    regdate TIMESTAMP DEFAULT NOW(),
    selected TINYINT(1) DEFAULT 0,
    primary key (`pk`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 공지사항 첨부 이미지
DROP TABLE IF EXISTS notice_img;
CREATE TABLE notice_img (
	pk int(11) NOT NULL AUTO_INCREMENT,
	noticePk int(11) NOT NULL,
    oriName VARCHAR(300) DEFAULT NULL,
	saveName VARCHAR(300) DEFAULT NULL,
    imgPath VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY (pk),
    FOREIGN KEY (noticePk) REFERENCES notice (pk)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 지도 좌표 (사직로 161)
DROP TABLE IF EXISTS coord;
CREATE TABLE coord (
    coordX DECIMAL(10, 8) DEFAULT 37.577976,
    coordY DECIMAL(11, 8) DEFAULT 126.975189
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 좌표 기본값 설정 
INSERT INTO coord VALUES (37.577976, 126.975189);

-- 가이드북 첨부
DROP TABLE IF EXISTS guidebook;
CREATE TABLE guidebook (
	pk INT(11) NOT NULL AUTO_INCREMENT,
	lang VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    oriName VARCHAR(300) DEFAULT NULL,
	saveName VARCHAR(300) DEFAULT NULL,
    filePath VARCHAR(500) DEFAULT NULL,
    updateTime TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (pk)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 경회루 특별관람 예약
DROP TABLE IF EXISTS sp_tour;
CREATE TABLE sp_tour (
	pk INT(11) NOT NULL AUTO_INCREMENT,
    id VARCHAR(100) NOT NULL,
    num INT(11) NOT NULL,
    bookDt TIMESTAMP DEFAULT NOW(),
    visitDt TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (pk)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 한국어 단체관람 예약
DROP TABLE IF EXISTS kr_tour;
CREATE TABLE kr_tour (
	pk INT(11) NOT NULL AUTO_INCREMENT,
    id VARCHAR(100) NOT NULL,
    num INT(11) NOT NULL,
    bookDt TIMESTAMP DEFAULT NOW(),
    visitDt TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (pk)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 경복궁의 역사
DROP TABLE IF EXISTS history;
CREATE TABLE history (
	year INT(11) NOT NULL,
    title VARCHAR(100) NOT NULL,
    detail VARCHAR(100) NOT NULL,
    primary key(`year`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;